blank_issues_enabled: true
contact_links:
  - name: ⭐ Sponsor Performance Monitor Analyser
    url: https://www.buymeacoffee.com/skarllot
    about: Help the continued development.
  - name: 💬 Ask on Github Discussions
    url: https://github.com/skarllot/perfmon-explorer/discussions
    about: The best place for asking general purpose questions.
